Javascript Library
Alexoid1/Library pull request #2
Opened 2020-10-27 20:56 UTC by jssarrazolaa

This is a project of the Javascript module. It is preceded by the lesson about Objects and the Object Constructor.
The library work with a form that gets the data and create the DOM elements in the file.

2020-10-27 22:04 UTC, kubilaycaglayan requested changes
#### Hello Team 👋
#### Status: Changes Required ♻️

Great job so far! 👏👋
Let's cover a few details together to make your project better 😊⏬

## GitFlow

- [x] [REQUIRED] Set your `development` branch as default.

## DOM manipulation vs. Application Logic

- [ ] [REQUIRED] Keep the application logic separated from DOM manipulation tasks ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) from Pathwright)

💡 Check the inline comments below please.

## Display Book

Okay, this is mostly about the usage of the `booksContainer` array. I will give you some additional information, follow the bulbs 💡 please :blush:.

- [ ] [REQUIRED] It has a function that loops through the array and displays each book ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/books_render_loop.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

💡 Currently, you have an array `booksContainer` to store the books but you are not using that array to show the books.
You are creating components at the moment the submit button clicked. This fine but the components(containers) or book cards should be created by looping through the `booksContainer` array.

- [ ] [REQUIRED] It displays on the page every book contained in the array ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/render_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

💡 In other words, if we initialize the application with this array `const myLibrary = [new Book('title', 'author', 'pages', 'status')];` we should be able to see that book at the beginning.

- [ ] [REQUIRED] Each `Book` displayed has a `button` to `remove` the `Book` from the `Library` array ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/remove_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

💡 The idea is similar here. We need a button to remove the books from the array, therefore from the view.

- [ ] [REQUIRED] Each `Book` displayed has a `button` to `toggle` the `Book` read status ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/toggle_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

💡 Currently, we have this button but it should alter the objects in the array.

#### :arrow_right:  Imagine that array(`myLibrary`) is your Database and whenever you need to make a change you have to first change the Database.

## Here are some optional requirements if you want to go further and learn more 😇

- [ ] [OPTIONAL] the form used to create a book should have validations, you should not be able to create an empty book

- [ ] [OPTIONAL] It has data persistence by saving, retrieving, and updating the library books using [the localstorage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/localstorage_stretch_requirement.png) from [Odin Project](https://www.theodinproject.com/courses/javascript/lessons/library))

## That's it, you can submit another code review request after making these changes ♻️ 😇

With all my respect 🙏
> Kubilay Caglayan | Technical Support Engineer

2020-10-27 22:04 UTC, kubilaycaglayan commented on app.js
> +    }
:bulb: This is a little part of application logic. And it is happening in the DOM manipulation method. It is better to make an isolated function to change the status of a specific book in the array and call it here.

2020-10-27 22:06 UTC, MuriloRoque requested changes
## Status: Changes requested 🔴 

### Hello again @jssarrazolaa and @Alexoid1 👋 

### You have started really well, your page is almost perfect, we just need to fix some details before moving forward, alright?

- [x] Please check my comments in your code.

- [ ] Add a nice screenshot to your README file.

- [ ] In general, your functions are doing their job, but we need some refactoring:

- Separate your functions into more small functions, so they are not too big and hard to read. The below requirement will probably help with that.
- Keep your application logic separated from the DOM manipulation tasks ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) from Pathwright). This is a hard one, but I will try helping you here. Create another JS file for DOM manipulation functions, like `document.getElementById` or `document.createElement`. In your main file, keep only logic related code that won't 'mess up' with the DOM, call these functions from your DOM manipulation file.

## Summary

- Your repository is very professional, keep up the good work 💪 
- Your page is doing what it needs to do, except for deleting a book 🚀 
- We just need to work a little more on the requirements I mentioned and we will be ready to go 👍 

Kindly make the requested changes and submit for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)

2020-10-27 22:06 UTC, MuriloRoque commented on app.js
> +  create(book, booksContainer);
- [x] Your function `addBookToLibrary` only pushes a book into an array, why don't you just delete that function and put the statement inside the `addBook` function. Also, rename the function `addBook` to `addBookToLibrary`, so we can be on par with the requirements ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/book_array_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

2020-10-27 22:06 UTC, MuriloRoque commented on index.html
> +                <input type='submit' id='button'>
- [x] Change the name of the button from `Enviar` to `New Book`, so everything is in English 😉 (P.S.: It looks like we have a Brazilian here, "Olá, meu amigo! 😄")

2020-10-27 22:06 UTC, MuriloRoque commented on app.js
> +function create(book) {
- [x] This function should loop through the `myLibrary` array and display each book in your book container, you are just creating the elements in your page. For example, why did you create the array if you are not using it for anything but push books inside? ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/books_render_loop.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

- [x] We also need a function to delete a book from the array ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/remove_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

2020-10-27 22:22 UTC, MuriloRoque commented
### Hello again @jssarrazolaa and @Alexoid1 👋 

### I know you got two reviews from two different TSEs, it was probably a bug in our Dashboard. 

### But don't worry, we will try merging our reviews so you get only one list of requirements, can you please wait a little bit?

### Thank you

2020-10-27 22:30 UTC, MuriloRoque commented
### Hello @jssarrazolaa and @Alexoid1 👋 

### We are very sorry about this bug, but we have decided to leave both our feedbacks in your Pull Request 😄 

### Since Kubilay suggested changes first, you may only follow his suggestions (for fairness), BUT it would be a huge plus if you could follow mine too, so your project can get even better!

### Happy coding! 💻

2020-10-28 16:42 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Sorry for the bug as the previous reviewer mentioned! 🙏 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-10-28 16:46 UTC, merged